import type { Metadata } from "next";
import "@/css/satoshi.css";
import "@/css/style.css";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="text-black">
        
        {children}</body>
    </html>
  );
}
